#!/bin/bash

# 部署目录
ROOT_DIR="/var/www/site/oneblog/$2"
# 部署的项目名
APP_NAME=blog-$2.jar
NOW_DATE=$(date +%c)

usage() {
    echo "
Copyright @ https://www.zhyd.me . Current Version : v1.0.0

使用方法:
    oneblog [options] [modules]
    [options]
        start                : 启动
        stop                 : 停止
        restart              : 重启
        status               : 状态
        log                  : 实时监控日志
    [modules]
        web                  : 前台程序(blog-web)
        admin                : 后台程序(blog-admin)
示例:
    oneblog start web
    oneblog stop web
    oneblog restart web
    oneblog status web
    oneblog log web

注：如果脚本无法执行（报异常），请使用dos2unix命令编译（需先安装：yum install dos2unix）
"
    exit 1
}

is_exist_dir() {
    if [[ -d "${ROOT_DIR}" ]]; then
        return 1
    else
        return 0
    fi
}

is_running(){
  pid=`ps -ef|grep $APP_NAME|grep -v grep|awk '{print $2}' `
  if [ -z "${pid}" ]; then
   return 1
  else
    return 0
  fi
}

start(){
  is_running
  if [ $? -eq "0" ]; then
    echo "${APP_NAME} 正在运行。 pid=${pid} ."
  else
    nohup java -server -Xms256m -Xmx512m -jar ${ROOT_DIR}/$APP_NAME &
    echo "${APP_NAME}启动成功，请查看日志确保运行正常。"
    fi
}

stop(){
  is_running
  if [ $? -eq "0" ]; then
    kill -9 $pid
    echo "${pid} 进程已被杀死，程序停止运行"
  else
    echo "${APP_NAME} 未运行！"
  fi
}

status(){
  is_running
  if [ $? -eq "0" ]; then
    echo "${APP_NAME} 正在运行。Pid is ${pid}"
  else
    echo "${APP_NAME} 未运行！"
  fi
}

log(){
  echo "日志文件位置：${ROOT_DIR}/nohup.out"
  tail -f ${ROOT_DIR}/nohup.out
}

restart(){
  stop
  start
  log
}

is_exist_dir
if [ $? != 0 ]; then
    echo "当前时间：${NOW_DATE}"
    case "$1" in
      "start")
        start
        ;;
      "stop")
        stop
        ;;
      "status")
        status
        ;;
      "restart")
        restart
        ;;
      "log")
        log
        ;;
      *)
        usage
        ;;
    esac
else
    echo -e "不存在的ROOT_DIR路径[${ROOT_DIR}]! 请检查脚本配置后重试"
fi
